= telegraf-formula

https://travis-ci.com/saltstack-formulas/telegraf-formula[image:https://travis-ci.com/saltstack-formulas/telegraf-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

Formula to set up and configure telegraf

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Available states

=== `telegraf`

Installs and configures the telegraf package from upstream repository.

=== `telegraf.repo`

Installs the telegraf repository. See
https://docs.influxdata.com/telegraf/v1.11/introduction/installation/#installation[Telegraf
doc] for more details.

=== `telegraf.package`

Installs the telegraf package.

=== `telegraf.config`

This state manages the file `telegraf.conf` under `/etc/telegraf`
(template found in "telegraf/files"). The configuration is populated by
values in "telegraf/map.jinja" based on the package's default values
(and RedHat, Debian, Suse and Arch family distribution specific values),
which can then be overridden by values of the same name in pillar.

=== `telegraf.service`

Manages the startup and running state of the telegraf service.

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `telegraf` main state, ready
for testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.
